Lidar_front_end:
   lidar_type: 1   # 1 for Livox-avia, 3 for Ouster-OS1-64
   N_SCANS: 1
   using_raw_point: 1
   point_step: 4
   
r3live_common:
   if_dump_log: 0                   # If recording ESIKF update log. [default = 0]
   record_offline_map: 1            # If recording offline map. [default = 1]
   pub_pt_minimum_views: 3          # Publish points which have been render up to "pub_pt_minimum_views" time. [default = 3]
   minimum_pts_size: 0.01           # The minimum distance for every two points in Global map (unit in meter). [default = 0.01] 
   image_downsample_ratio: 1        # The downsample ratio of the input image. [default = 1]
   estimate_i2c_extrinsic: 0        # If enable estimate the extrinsic between camera and IMU. [default = 1] 
   estimate_intrinsic: 0            # If enable estimate the online intrinsic calibration of the camera lens. [default = 1] 
   maximum_vio_tracked_pts: 600     # The maximum points for tracking. [default = 600]
   append_global_map_point_step: 4  # The point step of append point to global map. [default = 4]

r3live_vio:
   image_width: 848
   image_height: 800
   camera_intrinsic:
      [286.67529296875, 0.0, 420.8309020996094, 0.0, 286.4482116699219, 400.664794921875, 0.0, 0.0, 1.0 ] 
   camera_dist_coeffs: [-0.009616331197321415, 0.04459955170750618, -0.04223119840025902, 0.007682282943278551, 0]  #k1, k2, p1, p2, k3
   # Fine extrinsic value. form camera-LiDAR calibration.
   camera_ext_R:
         [-0.00530814, -0.23932, 0.970926,
          -0.99973, -0.0206819, -0.0105634,
          0.0226086, -0.97072, -0.239146]
   #camera_ext_t: [1.8733e-01, -4.1228e-03, -2.0341e-01] 
   camera_ext_t: [0.00147137, -0.152703, -0.230572] 
   
r3live_lio:        
   lio_update_point_step: 4   # Point step used for LIO update.  
   max_iteration: 2           # Maximum times of LIO esikf.
   lidar_time_delay: 0        # The time-offset between LiDAR and IMU, provided by user. 
   filter_size_corner: 0.30   
   filter_size_surf: 0.30
   filter_size_surf_z: 0.30
   filter_size_map: 0.30
